<?php

/**
 * @file
 * Functions to support theming in the SASS Starterkit subtheme.
 */

use Drupal\Core\Extension\ModuleExtensionList;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_system_theme_settings_alter() for settings form.
 *
 * Replace Barrio setting options with subtheme ones.
 *
 * Example on how to alter theme settings form
 */
function pharmacy_form_system_theme_settings_alter(&$form, FormStateInterface $form_state)
{
    $form['components']['navbar']['bootstrap_barrio_navbar_top_background']['#options'] = [
        'bg-primary' => t('Primary'),
        'bg-secondary' => t('Secondary'),
        'bg-light' => t('Light'),
        'bg-dark' => t('Dark'),
        'bg-white' => t('White'),
        'bg-transparent' => t('Transparent'),
    ];
    $form['components']['navbar']['bootstrap_barrio_navbar_background']['#options'] = [
        'bg-primary' => t('Primary'),
        'bg-secondary' => t('Secondary'),
        'bg-light' => t('Light'),
        'bg-dark' => t('Dark'),
        'bg-white' => t('White'),
        'bg-transparent' => t('Transparent'),
    ];
}

/**
 * Custom side menus fro mexposed filters builder.
 * 
 * @param mixed $variables 
 * 
 * @return void 
 */
function pharmacy_preprocess_bef_links(&$variables)
{
    if (false === empty($variables['selected'])) {
        $selected = array_keys($variables['selected']);
        $selected = array_shift($selected);
        $variables['active_elements'] = [];

        if ($variables['depth'][$selected] > 0) {
            $variables['active_elements'][] = $selected;
            $curr_depth = intval($variables['depth'][$selected]);
            $slice_end = array_search($selected, array_keys($variables['depth']));
            $reverse_search = array_slice($variables['depth'], 0, $slice_end, true);
            $search = array_reverse($reverse_search, true);

            foreach ($search as $parent => $new_depth) {
                if (intval($new_depth) < $curr_depth) {
                    $variables['active_elements'][] = $parent;
                    $curr_depth = intval($new_depth);
                }

                if ($curr_depth === 0) {
                    break;
                }
            }
        }
    }
}
