<?php

use Drupal\assorted_fixes\Plugin\Block\CartBlock;
use Drupal\assorted_fixes\Plugin\Commerce\CheckoutPane\MiniLogin;
use Drupal\assorted_fixes\Plugin\Commerce\CheckoutPane\SortedShippingInformation;

/**
 * Implements hook_block_alter().
 *
 * Replaces the commerce_cart CartBlock block with the commerce_cart_flyout one.
 */
function assorted_fixes_flyout_block_alter(array &$info)
{
    $info['commerce_cart']['class'] = CartBlock::class;
    $info['commerce_cart']['provider'] = 'assorted_fixes';
}

/**
 * Implements hook_commerce_checkout_pane_info_alter().
 */
function assorted_fixes_commerce_checkout_pane_info_alter(array &$info)
{
    if (isset($info['shipping_information'])) {
        $info['shipping_information']['class'] = SortedShippingInformation::class;
        $info['shipping_information']['provider'] = 'assorted_fixes';
    }

    if (isset($info['login'])) {
        $info['login']['class'] = MiniLogin::class;
        $info['login']['provider'] = 'assorted_fixes';
    }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function assorted_fixes_form_commerce_checkout_flow_multistep_default_alter(
    &$form,
    &$form_state,
    $form_id
) {
    if (false === empty($form['login']) && false === empty($form['contact_information'])) {
        // print_r('<pre>');
        // print_r(array_keys($form['login']['register']));
        // exit();
        $tmp = [
            'contact_information' => $form['contact_information'],
            'text' => $form['login']['guest']['text'],
            'continue' => $form['login']['guest']['continue'],
        ];
        unset(
            $form['login']['guest']['text'],
            $form['login']['guest']['continue']
        );
        $form['login']['guest'] = array_merge($form['login']['guest'], $tmp);
        unset($form['contact_information'], $tmp);
    }
}