<?php

use Drupal\assorted_fixes\Plugin\Block\CartBlock;
use Drupal\assorted_fixes\Plugin\Commerce\CheckoutPane\SortedShippingInformation;

/**
 * Implements hook_block_alter().
 *
 * Replaces the commerce_cart CartBlock block with the commerce_cart_flyout one.
 */
function assorted_fixes_flyout_block_alter(array &$info)
{
    $info['commerce_cart']['class'] = CartBlock::class;
    $info['commerce_cart']['provider'] = 'assorted_fixes';
}

/**
 * Implements hook_commerce_checkout_pane_info_alter().
 */
function assorted_fixes_commerce_checkout_pane_info_alter(array &$info)
{
    if (isset($info['shipping_information'])) {
        $info['shipping_information']['class'] = SortedShippingInformation::class;
        $info['shipping_information']['provider'] = 'assorted_fixes';
    }
}